### ISSUE TITLE
记忆

### ISSUE THREAD

**Issue by noctiro** [InJeCTrL/ClickRun#1]
这个软件很不错，但可以加个记忆功能吗？我每次打开都要重新设置，不太方便。

**Comment by InJeCTrL** [comment]
感谢你的使用，[2020-07-10的更新](https://github.com/InJeCTrL/ClickRun/releases/tag/1.0)中加入了配置信息读取与记录功能，程序运行后尝试读取记录并显示，每次锁定配置后记录配置信息到注册表。感谢你的建议。
