### ISSUE TITLE
在逆战游戏里面不起作用啊

### ISSUE THREAD

**Issue by x420520** [InJeCTrL/ClickRun#4]
不知道有没有遇见和我一样问题的老哥，我想在 逆战游戏里面使用，但是不起作用啊

**Comment by x420520** [comment]
本人尝试了 切换模拟方式 开启管理员权限，但是均无效。

**Comment by InJeCTrL** [comment]
逆战是运行在DirectX上的游戏，这类型游戏通过DXInput读取输入，属于比较底层的操作，本程序中的两种Win32API无法在这类型游戏中起作用。
