### ISSUE TITLE
<提问>鼠标左键出现误触情况

### ISSUE THREAD

**Issue by ZixiongBillLi** [InJeCTrL/ClickRun#5]
很不错的软件！但是不知道是不是我的问题，最近使用过后开始出现一个问题：即使关闭程序后，手动按下鼠标左键的时候也会不时判定多次点击
目前只在鼠标上出现，触控板和数位板目前没有发现
请问有没有什么解决方案？谢谢！

**Comment by InJeCTrL** [comment]
感谢您对ClickRun的支持！因为该程序仅调用了Win32API实现模拟击键，不会绑定鼠标左键点击事件，所以个人认为您的情况可能与该程序无关，建议您尝试更换其它鼠标后尝试是否会复现同样问题！
